name:         eqlib
version:      0.4.1
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Equation manipulation library
homepage:     https://github.com/eqdb/eqlib
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  test:       ^0.12.15+11
  collection: ^1.13.0
