name:         eqlib
version:      0.1.1
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Equation manipulation library
homepage:     https://github.com/eqdb/eqlib
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  quiver:     ^0.23.0
dev_dependencies:
  test:       ^0.12.15+11
