name:         eqlib
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Equation manipulation library
homepage:     https://github.com/eqdb/eqlib
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  quiver:     ^0.23.0
dev_dependencies:
  test:       ^0.12.15+11
  browser:    ^0.10.0+2
  angular2:   ^2.0.0
  katex_js:   ^0.1.0+1
  guppy_dart: ^0.0.3
  math_expressions:       ^0.3.0
  angular2_components:    ^0.1.1
  dart_sass_transformer:  ^0.5.0+1
transformers:
- dart_sass_transformer:
    style:                compact
- angular2:
    entry_points:         web/notebook.dart
    platform_directives:  package:angular2/common.dart#CORE_DIRECTIVES
